In [ ]:
import torch
import numpy as np

# 1: Create a 3x3 tensor with random numbers between 0 and 1.


In [ ]:
tensor_a=torch.rand(3,3)
tensor_a

tensor([[0.0513, 0.4549, 0.1968],
        [0.7498, 0.9164, 0.7187],
        [0.7597, 0.6638, 0.6126]])

# 2: Create another 3x3 random tensor for operations.

In [ ]:
tensor_b=torch.rand(3,3)
tensor_b

tensor([[0.6416, 0.0684, 0.9996],
        [0.7918, 0.2307, 0.7853],
        [0.2109, 0.5974, 0.1764]])

# 3: Perform matrix addition.

In [ ]:
addition=tensor_a+tensor_b
addition

tensor([[0.6929, 0.5233, 1.1964],
        [1.5416, 1.1472, 1.5040],
        [0.9706, 1.2611, 0.7890]])

# 4: Perform matrix multiplication.

In [ ]:
multiplication=torch.matmul(tensor_a,tensor_b)
multiplication

tensor([[0.4347, 0.2261, 0.4433],
        [1.3583, 0.6920, 1.5959],
        [1.1422, 0.5710, 1.3887]])

# OR

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2451, 0.8859, 0.9802],
        [0.6791, 0.8141, 0.5524],
        [0.4084, 0.7738, 0.7070]])

# 5: Transpose the multiplication result.

In [ ]:
Transposed=multiplication.T
Transposed

tensor([[0.4347, 1.3583, 1.1422],
        [0.2261, 0.6920, 0.5710],
        [0.4433, 1.5959, 1.3887]])

In [ ]:
print(type(Transposed))

<class 'torch.Tensor'>


# 6: Convert to NumPy array.

In [ ]:
numpy_array = Transposed.numpy()
numpy_array

array([[0.43465143, 1.3582573 , 1.1421796 ],
       [0.22606803, 0.6920183 , 0.5710378 ],
       [0.44327554, 1.5959414 , 1.3887086 ]], dtype=float32)

In [ ]:
print(type(numpy_array))

<class 'numpy.ndarray'>


# 7: Reshape into (1, 9).

In [ ]:
reshaped_tensor = torch.tensor(numpy_array.reshape(1, 9))
reshaped_tensor

tensor([[0.4347, 1.3583, 1.1422, 0.2261, 0.6920, 0.5710, 0.4433, 1.5959, 1.3887]])

In [ ]:
reshaped_tensor.shape

torch.Size([1, 9])